### ISSUE TITLE
Could not initialize class `com.amazonaws.services.lambda.AWSLambdaAsyncClientBuilder`

### ISSUE THREAD

**Issue by kostyaplis** [Nordstrom/kafka-connect-lambda#38]
Trying to launch Lambda Connector with most basic options from provided example.

Running strimzi/kafka:0.17.0-kafka-2.4.0, kafka-connect-lambda:1.2.2

Config:

```json
{
  "connector.class": "com.nordstrom.kafka.connect.lambda.LambdaSinkConnector",
  "aws.region": "ap-southeast-1",
  "topics": "single.topic.here",
  "tasks.max": "1",
  "aws.lambda.function.arn": "arn:aws:lambda:ap-southeast-1:xxx:function:xxx",
  "value.converter": "org.apache.kafka.connect.storage.StringConverter",
  "key.converter": "org.apache.kafka.connect.storage.StringConverter",
  "aws.lambda.batch.enabled": "false"
}
```

Keep getting an error : 
```
2020-07-02 09:00:18,082 ERROR WorkerConnector{id=personalize-aws-lambda} Error while starting connector (org.apache.kafka.connect.runtime.WorkerConnector) [DistributedHerder-connect-1]
java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.services.lambda.AWSLambdaAsyncClientBuilder
	at com.nordstrom.kafka.connect.lambda.InvocationClient$Builder.<init>(InvocationClient.java:126)
	at com.nordstrom.kafka.connect.lambda.InvocationClientConfig.<init>(InvocationClientConfig.java:55)
	at com.nordstrom.kafka.connect.lambda.LambdaSinkConnectorConfig.<init>(LambdaSinkConnectorConfig.java:52)
	at com.nordstrom.kafka.connect.lambda.LambdaSinkConnector.start(LambdaSinkConnector.java:31)
	at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:110)
	at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:135)
	at org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:195)
	at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:257)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:1183)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.processConnectorConfigUpdates(DistributedHerder.java:541)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:388)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:282)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Any help highly appreciated!

**Comment by dylanmei** [comment]
This is addressed with 1.3.0 release.
