### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by arnitolog** [Nordstrom/kafka-connect-lambda#40]
Hello, 
I'm receiving the below error when I try to start this connector:
```
java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.services.lambda.AWSLambdaAsyncClientBuilder
              at com.nordstrom.kafka.connect.lambda.InvocationClient$Builder.<init>(InvocationClient.java:126)
              at com.nordstrom.kafka.connect.lambda.InvocationClientConfig.<init>(InvocationClientConfig.java:55)
              at com.nordstrom.kafka.connect.lambda.LambdaSinkConnectorConfig.<init>(LambdaSinkConnectorConfig.java:52)
              at com.nordstrom.kafka.connect.lambda.LambdaSinkConnector.start(LambdaSinkConnector.java:31)
              at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:110)
              at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:135)
              at org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:195)
              at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:257)
              at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:1190)
              at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1300(DistributedHerder.java:126)
              at org.apache.kafka.connect.runtime.distributed.DistributedHerder$10.call(DistributedHerder.java:908)
              at org.apache.kafka.connect.runtime.distributed.DistributedHerder$10.call(DistributedHerder.java:894)
              at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:349)
              at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:289)
              at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
              at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
              at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
              at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
              at java.base/java.lang.Thread.run(Thread.java:834)
```
I tried to add aws-java-sdk-1.11.873.jar file in the libs folder for Kafka Connet, but it didn't help.
Also, I tried to use a compiled (compiled from source on my laptop) version of the connector jar. But got the same result
Could you please advise what I did wrong

**Comment by arnitolog** [comment]
solved by compiling from the source
